### ISSUE TITLE
Question : How to use card.io for android app with cordova

### ISSUE THREAD

**Issue by xuanlocnet** [card-io/card.io-Cordova-Plugin#42]
Dear,
I have a problem when using this plugin.
After i install, i can able to open the camera, but after that nothing happen, even though i tried with other visa cards and i use also visa card on google but it still not able to capture or get any information from these credit cards.
So, my question here about  : Does i need to install any other plugin and any way to use it or just install this plugin is enough?
Because i tried to use also example code of this plugin, but it still show the camera to me and nothing next.
I really need your support.
Thanks.

**Comment by lolptdr** [comment]
What errors do you get in console? What version of Android? How did you implement the code for this plugin? Be aware of runtime permissions on Android M: http://cordova.apache.org/docs/en/latest/guide/platforms/android/plugin.html#android-permissions

**Comment by xuanlocnet** [comment]
My device is Asus Zenfone 5 with Android version 5.0
This is ionic info : 
Cordova CLI: 6.2.0
Ionic Framework Version: 1.1.0
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0-beta.20
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.4 LTS 
Node Version: v4.4.7

It still show the camera and it still can focus to credit card, but it not show any error or return anything to me.
I mean that when i run this code, it open camera and still keep on showing camera and i can saw credit card on camera screen but nothing happen after that. It still keep on camera screen.

![image 2](https://cloud.githubusercontent.com/assets/2188779/18242165/258191d8-737f-11e6-853d-deb1cd8e0ff1.jpeg)

![image 2](https://cloud.githubusercontent.com/assets/2188779/18242147/0589c828-737f-11e6-8a5c-3440e5370cd1.jpeg)

**Comment by dgoldman-ebay** [comment]
@xuanlocnet the particular card in your images does not have a valid credit/debit card number.

These numbers use the Luhn algorithm to generate a check digit. (You can easily find online validators for Luhn check-digits.) For a card number beginning `40001234567890`, the check digit should be `7` rather than the `0` in your sample card.

So for this particular card, card.io is not recognizing it because the card number is not a valid one.

(If you are also seeing failures with other cards, there might be different reasons that card.io does not recognize those other cards.)

**Comment by lolptdr** [comment]
@xuanlocnet: See my forked commits if this helps #44

**Comment by xuanlocnet** [comment]
Thank you @dgoldman-ebay and @lolptdr for your supporting, it work for me.
This is a awesome plugin.

**Comment by CHOMNANP** [comment]
@xuanlocnet: Appreciate if you could share how do you get this working with IONIC?
I tried and it doesn't work.

Thanks,
Punleu
